server:
  port: 8761  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    preferIpAddress: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
