server:
  port: 8055

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
spring:
  data:
    mongodb:
      database: acc
      host: ec2-54-93-212-62.eu-central-1.compute.amazonaws.com
