sudo: required
language: java
jdk: oraclejdk8
dist: trusty
install: true

cache:
  directories:
    - $HOME/.m2


addons:
  sonarcloud:
    organization: "ahosny-repo"
    token:
      secure: aab8973204f9cf9d6b1345ed63f7a523f9fdd74a

script:
    - cd acc-discovery
    - mvn clean install
    - sonar-scanner
    
    - cd ../acc-config
    - mvn clean install
    - sonar-scanner
    
    - cd ../acc-car
    - mvn clean install
    - sonar-scanner

    - cd ../acc-customer
    - mvn clean install
    - sonar-scanner
    
    - cd ../acc-gateway
    - mvn clean install
    - sonar-scanner
    
    - cd ../acc-car-client
    - mvn clean install
    - sonar-scanner
    
    - cd ../acc-hystrix-monitor
    - mvn clean install
    - sonar-scanner