sudo: required
language: java
jdk: oraclejdk8
dist: trusty
install: true

cache:
  directories:
    - $HOME/.m2


addons:
  sonarcloud:
    organization: "ahosny-repo"
    token:
      secure: d73f7f526535fdf25116e55e46a5cf4bf4cad7c7
      
services:

    - docker
    
before_install:

     - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - cd acc-discovery
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-discovery:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-discovery:$TRAVIS_BUILD_ID
       
after_success:
    - docker --version  # document the version travis is using
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region eu-central-1)
    - docker build -t acc-project/acc-discovery:latest .
    - docker tag acc-project/acc-discovery:latest 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-discovery:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-discovery:latest