sudo: required
language: java
jdk: oraclejdk8
dist: trusty
install: true

cache:
  directories:
    - $HOME/.m2


addons:
  sonarcloud:
    organization: "ahosny-repo"
    token:
      secure: d73f7f526535fdf25116e55e46a5cf4bf4cad7c7
      
services:

    - docker
    
before_install:

     - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - cd acc-discovery
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
    - cd ../acc-config
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
    - cd ../acc-customer
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
    - cd ../acc-gateway
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
    - cd ../acc-car-client
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
        
    - cd ../acc-turbine-stream
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
    - cd ../acc-customer-car
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
    - cd ../acc-dashboard
    - docker build -t $DOCKER_USERNAME/acc-dashboard:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-dashboard:$TRAVIS_BUILD_ID
    
    - cd ../acc-car
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
    - cd ../acc-hystrix-monitor
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    
after_success:
    - docker --version  # document the version travis is using
    - sudo apt install python3-pip
    - pip3 --version
    - pip3 install awscli --upgrade --user
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region eu-central-1)
    - docker tag acc-discovery:latest 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-discovery:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-discovery:latest