sudo: required
language: java
jdk: oraclejdk8
dist: trusty
install: true

cache:
  directories:
    - $HOME/.m2


addons:
  sonarcloud:
    organization: "ahosny-repo"
    token:
      secure: d73f7f526535fdf25116e55e46a5cf4bf4cad7c7
      
services:

    - docker
    
before_install:

     - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:

    - cd acc-discovery
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-discovery:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-discovery:$TRAVIS_BUILD_ID
    
    - cd ../acc-config
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-config:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-config:$TRAVIS_BUILD_ID
    
    - cd ../acc-customer
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-customer:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-customer:$TRAVIS_BUILD_ID
    
    - cd ../acc-gateway
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-gateway:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-gateway:$TRAVIS_BUILD_ID
    
    - cd ../acc-car-client
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-car-client:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-car-client:$TRAVIS_BUILD_ID
        
    - cd ../acc-turbine-stream
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-turbine-stream:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-turbine-stream:$TRAVIS_BUILD_ID
   
    - cd ../acc-customer-car
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-customer-car:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-customer-car:$TRAVIS_BUILD_ID
    
    - cd ../acc-dashboard
    - docker build -t $DOCKER_USERNAME/acc-dashboard:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-dashboard:$TRAVIS_BUILD_ID
    
    - cd ../acc-car
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-car:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-car:$TRAVIS_BUILD_ID
    
    - cd ../acc-hystrix-monitor
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
    - docker build -t $DOCKER_USERNAME/acc-hystrix-monitor:$TRAVIS_BUILD_ID .
    - docker push $DOCKER_USERNAME/acc-hystrix-monitor:$TRAVIS_BUILD_ID
       
after_success:
    - docker --version
    - pip install --user awscli
    
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region eu-central-1)
    
    - docker tag $DOCKER_USERNAME/acc-discovery:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-discovery:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-discovery:latest
    
    - docker tag $DOCKER_USERNAME/acc-config:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-config:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-config:latest
    
    - docker tag $DOCKER_USERNAME/acc-customer:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-customer:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-customer:latest
    
    - docker tag $DOCKER_USERNAME/acc-gateway:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-gateway:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-gateway:latest
    
    - docker tag $DOCKER_USERNAME/acc-car-client:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-car-client:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-car-client:latest
    
    - docker tag acc-project/acc-turbine-stream:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-turbine-stream:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-turbine-stream:latest
    
    - docker tag $DOCKER_USERNAME/acc-customer-car:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-customer-car:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-customer-car:latest
    
    - docker tag $DOCKER_USERNAME/acc-dashboard:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-dashboard:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-dashboard:latest
    
    - docker tag $DOCKER_USERNAME/acc-car:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-car:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-car:latest    
    
    - docker tag $DOCKER_USERNAME/acc-hystrix-monitor:$TRAVIS_BUILD_ID 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-hystrix-monitor:latest
    - docker push 643749069809.dkr.ecr.eu-central-1.amazonaws.com/acc-project/acc-hystrix-monitor:latest