server:
  port: 8888
spring:  profiles:    active:    - native  cloud:    config:      server:        native:          search-locations:          - classpath:config
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
      management:  endpoints:    web:      exposure:        include:        - '*'