server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: 
        - '*'

turbine:
  app-config: acc-car,acc-customer,acc-customer-car
  cluster-name-expression: new String("default")
